drop table if exists test;

create table test (
        id bigint generated by default as identity,
        text varchar(255),
        primary key (id)
    );

insert into test(text) values ('thanks for querying me!');
